"xlsx_url": "./MDX_3007_histochoice/3007 histochoice kmeans4 DEGs GEX.xlsx"
"sheet_name": "differential_expression sel col"
"gene_set_names" : ["Hallmark", "GO_BP", "GO_MF", "GO_CC", "C8"]
"urls": [
  "./MDX_3007_histochoice/msigdb_v2025.1.Hs_GMTs/h.all.v2025.1.Hs.symbols.gmt",
  "./MDX_3007_histochoice/msigdb_v2025.1.Hs_GMTs/c5.go.bp.v2025.1.Hs.symbols.gmt",
  "./MDX_3007_histochoice/msigdb_v2025.1.Hs_GMTs/c5.go.mf.v2025.1.Hs.symbols.gmt",
  "./MDX_3007_histochoice/msigdb_v2025.1.Hs_GMTs/c5.go.cc.v2025.1.Hs.symbols.gmt", 
  "./MDX_3007_histochoice/msigdb_v2025.1.Hs_GMTs/c8.all.v2025.1.Hs.symbols.gmt"   
        ]
"output_dir" : "./MDX_3007_histochoice/test_output"
"clusters" : 4